apiVersion: v1
kind: Service
metadata:
   name: wordpress-lb
   namespace: wordpress-test
spec:
   type: LoadBalancer
   ports:
   -  protocol: TCP  
      port: 80
      targetPort: 80
      name: http
   selector:
      role: wordpress
